version: "3.8"
services:
  library-backend:
    image: 'library:latest'
    build:
      context: .
    container_name: library-backend
    restart: always
    ports:
    - "8080:8080"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodbb
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
##  mongo-express:
##    image: mongo-express
##    container_name: mongo-expresss
##    restart: always
##    ports:
##      - 8081:8081
##    environment:
##      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
##      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
##      - ME_CONFIG_MONGODB_SERVER=mongodb
#volumes:
  data: {}
#networks:
#  default:
#    driver: mongodb_network
#  app-tier:
#    driver: bridge


#  postgresql-slave:
#    image: 'bitnami/postgresql:11'
#    container_name: slave-1
#    networks:
#      - app-tier
#    restart: always
#    ports:
#      - '5434:5432'
#    depends_on:
#      - postgresql-master
#    environment:
#      - POSTGRESQL_REPLICATION_MODE=slave
#      - POSTGRESQL_REPLICATION_USER=replicator
#      - POSTGRESQL_REPLICATION_PASSWORD=replicator_pass
#      - POSTGRESQL_MASTER_HOST=postgresql-master
#      - POSTGRESQL_PASSWORD=zaq12wsx
#      - POSTGRESQL_MASTER_PORT_NUMBER=5432
#
#
#  postgresql-slave2:
#    image: 'bitnami/postgresql:11'
#    container_name: slave-2
#    restart: always
#    networks:
#      - app-tier
#    ports:
#      - '5435:5432'
#    depends_on:
#      - postgresql-master
#    environment:
#      - POSTGRESQL_REPLICATION_MODE=slave
#      - POSTGRESQL_REPLICATION_USER=replicator
#      - POSTGRESQL_REPLICATION_PASSWORD=replicator_pass
#      - POSTGRESQL_PASSWORD=zaq12wsx
#      - POSTGRESQL_MASTER_HOST=postgresql-master
#      - POSTGRESQL_MASTER_PORT_NUMBER=5432
