#version: '3'
#
#networks:
#  app-tier:
#    driver: bridge
#
#services:
#  library-backend:
#    image: 'library:latest'
#    build:
#      context: .
#    container_name: library-backend
#    restart: always
#    ports:
#    - "8080:8080"
#    networks:
#      - app-tier
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql-master:5432/library
#      - SPRING_DATASOURCE_USERNAME=library
#      - SPRING_DATASOURCE_PASSWORD=zaq12wsx
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
#    depends_on:
#      - postgresql-master

version: '3'

services:
  redis:
    image: redis:5.0.0
    container_name: master
    ports:
      - "6379:6379"
    networks:
      - redis-replication

  redis-slave-0:
    image: redis:5.0.0
    container_name: slave0
    ports:
      - "6380:6379"
    command: redis-server --slaveof master 6379
    depends_on:
      - redis
    networks:
      - redis-replication

  redis-slave-1:
    image: redis:5.0.0
    container_name: slave2
    ports:
      - "6381:6379"
    command: redis-server --slaveof master 6379
    depends_on:
      - redis-slave-0
    networks:
      - redis-replication

networks:
  redis-replication:
    driver: bridge